### ISSUE TITLE
unable to read USB filesystem if there is no partition table available 

### ISSUE THREAD

**Issue by ajayane** [magnusja/libaums#176] opened 2019-03-16 16:06 UTC
#### Stacktrace of Excpetion

```
(if exists)
```

**Comment by magnusja** [comment] 2019-03-16 19:19
This is implemented https://github.com/magnusja/libaums/pull/96

**Comment by ajayane** [comment] 2019-03-18 18:30
The problem was in MasterBootRecordCreator.read where you allocate a 512 buffer size and our disk block size was 4096. If you can set the buffer size to blockDevice.getBlockSize(), this will work like a charm!!. but dont know will it harm other devices... Anyways thanks for the fast reply.

**Comment by magnusja** [comment] 2019-03-20 11:05
You mean like https://github.com/magnusja/libaums/pull/177?

**Comment by ajayane** [comment] 2019-03-20 11:29
Yes!.Exactly. But I couldn't find the code fix in the pull..

**Comment by magnusja** [comment] 2019-03-20 11:39
What do you mean in th pull? This is an open PR so it is not merged to develop yet.

**Comment by magnusja** [comment] 2019-03-20 11:42
What kind of USB drive are you using? I have never seen a block size of 4096 and I really wonder what the problem is because the `ByteBlockDevice` reads 4096 bytes and discards the rest, so the MBR buffer should be OK.

There is now exception or anything?

**Comment by ajayane** [comment] 2019-03-20 11:43
Okay. Alright. Got it. It is an accessory with a block size of 4096 and FAT32 FS.

**Comment by ajayane** [comment] 2019-03-20 11:45
There was an exception when I changed the code and tested it worked well, If you can merge #177 to develop, it will be a great help.

**Comment by magnusja** [comment] 2019-03-20 13:24
Okay, can you maybe post the exception and stack trace here. I am curious why this happens.

I will merge when I verified it does not have any unexpected side effects.

Just checkout the branch fix/mbr-buffer-size for now

**Closed** 2019-12-09 14:13 UTC
