### ISSUE TITLE
corrupted and missing files 

### ISSUE THREAD

**Issue by MixApplications** [magnusja/libaums#233] opened 2019-12-01 05:50 UTC
missing files and corrupted files while copy from phone to usb 

 files name  looking like  bytes[].tostring() files name like : (  ïU¼â─R.h0   , ╝ëm╕k╦dï.]╝≈   , â∞ u└╟.  ,  p w wΘ.¬ )
<a href="https://ibb.co/RcTb93P"><img src="https://i.ibb.co/VTY9tgD/Untitled.png" alt="Untitled" border="0"></a>

file size not only 0 butes there is files its size larger than usb pen drive size

"volume label in non root dir!"  logcat

**Comment by magnusja** [comment] 2019-12-02 11:36
Hey there,

do you see these files also when you plug it back into your Android phone and use libaums? Do you see only additional junk files or do you also miss files which should be there? And again, what version are you using?

**Comment by MixApplications** [comment] 2019-12-03 17:19
Yes i see this files in Android too i using 0.7.2 version and this files can't delete it too i must format it

**Comment by magnusja** [comment] 2019-12-03 17:51
When you say ANdroid do you mean the Android system itself or the usbfileman app in this repo?

What do you extract? I `dd` the iso to a usb drive and plug it into my phone and then what?

**Comment by magnusja** [comment] 2019-12-03 18:25
![image](https://user-images.githubusercontent.com/1659457/70078269-ab6cc780-1602-11ea-9fe7-b7d1d3da4886.png)
I think I am finally able to reproduce this 🙌

**Comment by MixApplications** [comment] 2019-12-04 00:57
nice finally you understand me :)
sorry for bad English

**Comment by kuza2010** [comment] 2019-12-05 08:57
Hi, guys!✌ 
The firstly, I want to say, that it really amazing library!
But, unfortunately, I am facing this issue too. 
I try to copy a folder with mixed files from internal storage to USB.

After copy folder on usb looks like:
![image](https://user-images.githubusercontent.com/32107577/70218636-68226e00-1754-11ea-9734-faff3fbf80a4.png)

Please, let me know how I can help you.

**Comment by magnusja** [comment] 2019-12-09 11:05
Hey @kuza2010 @MixApplications 

can you please test the new version `0.7.3`

Thanks

**Comment by kuza2010** [comment] 2019-12-09 15:08
Hi @magnusja, I found your latest changes.
Now I **can't see** some ugly files! But, I getting a new error. I try to copy many files and in copy progress, I get the next error:
`java.io.IOException:` Could not write to device, result == -1 errno 0 null` 
Every time with different stack trace. 

For example, when I try OutputStream.write(byte):
![image](https://user-images.githubusercontent.com/32107577/70446762-a7cbbb80-1aae-11ea-9b47-8c64f0d7f2ec.png)

Any hints?

Thanks

**Comment by magnusja** [comment] 2019-12-09 15:17
This one is a nasty one. Maybe try another pen drive. Are you using the storage provider module?

**Comment by kuza2010** [comment] 2019-12-09 15:35
No, I am not using the storage provide module.
Okay, I will try it with another usb. I'll let you know what I can do.

Thanks a lot

**Comment by magnusja** [comment] 2019-12-09 15:39
Okay let me know how it goes. I will close this for now, feel free to ask some questions over gitter.

**Closed by magnusja** 2019-12-09 15:39 UTC
