### ISSUE TITLE
Uri to file path or usbFile to File

### ISSUE THREAD

**Issue by Qamar4P** [magnusja/libaums#70] opened 2017-03-14 15:32 UTC
Can't get path for usbFile
I try to extract thumbnail for video using 
`InputStream is = new UsbFileInputStream(usbFile);` not posible. 
Further problem is to play that video clip from USB in VideoView without copying.

**Comment by magnusja** [comment] 2017-03-14 16:51
File path #38

How exactly are you trying to get the thumbnail?

To avoid copying you can either use the http or the storageprovider module.

**Comment by Qamar4P** [comment] 2017-03-15 06:57
No success yet but hope to get thumbnail using following. https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FrameGrabber.java

**Comment by Qamar4P** [comment] 2017-03-15 09:40
Couldn't open file on client side; trying server side: java.io.IOException: setDataSourceFD failed.: status=0x80000000
03-15 14:39:42.183 7616-7616/com.citrusbits.leefaccess E/MediaPlayer: Unable to create media player
03-15 14:39:42.185 7616-7616/com.citrusbits.leefaccess W/VideoView: Unable to open content: content://com.citrusbits.leefaccess.usbstorage.documents/document/usb1002%3A%2FGOPR0462.MP4
                                                                    java.io.IOException: setDataSource failed.: status=0x80000000

**Comment by magnusja** [comment] 2017-03-15 16:42
Are you using the storage provider framework?

It seems that your VideoView does not support these kind of paths. Maybe try the http module instead.

**Comment by Qamar4P** [comment] 2017-03-16 07:22
@magnusja 
1. Yes, I am using [`UsbStorageProvider`](https://github.com/1hakr/AnExplorer/blob/master/app/src/main/java/dev/dworks/apps/anexplorer/provider/UsbStorageProvider.java)` extends DocumentsProvider`


2. [CommonsWare](www.github.com/commonsguy) mention that embedded web server has security ramifications [ref](http://stackoverflow.com/a/42784870/5710872). And further he said he will work with you on this library.

3. I also try wseemann/FFmpegMediaMetadataRetriever.

```
FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();
                        mmr.setDataSource(LeefApp.getInstance(),documentUri);
//                        mmr.setDataSource(fd);
                        bm = mmr.getFrameAtTime(2000000);
```

thank you. It's working now.

4. How to use this uri in video player and seek back and forth without any issue without copying it's content? Meanwhile I am working on it. You suggestion will help me.

**Comment by Qamar4P** [comment] 2017-03-17 01:28
@magnusja I am available for research and help to solve URI and file path issue.

**Comment by magnusja** [comment] 2017-03-17 17:05
Hey there,

1. There is no need to use this class from the AnExplorer project. This officially feature is supported. You only have to install the module libaums-storageprovider. See the documentation for more information on that.

2. I don't know what exactly he means. If you use the NanoHTTP library, you can set the address to 127.0.0.1, so only apps on the device itself can reach the server and no one else in the network. Other than that I cannot see any issues, maybe you can ask him instead?

4. Are you trying to play the video in your app or are you opening a 3rd party app via an intent? For the latter, it might be worth checking out the libaums-http module. Usually, 3rd party media players all have support for playing http URLs. If you are trying to embed the player in your app, you either have to find something that supports URIs from ContentProviders or you also try the http module.

Let me know how your tests go, thanks!

**Comment by Qamar4P** [comment] 2017-03-17 19:31
Thanks, 1/2 I was using. Fine.
3/4 using embedded player. I try Android media player. It was not working with uri. I will let you know if any player works with your lib.

**Comment by Qamar4P** [comment] 2017-03-27 05:28
@magnusja ExoPlayer is working but buffering more than ES Explorer built-in player.

**Comment by 46472761** [comment] 2017-04-06 16:30
JAMES LACONIA DAVIS,TRIPLE ELITE,46472761

**Comment by fly7632785** [comment] 2017-06-06 08:08
@magnusja 
hi,what a awesome framework.
but I need filePath ,too. Coz, It's forced by my Api to upload a File ,not a inputStream.  
So, I need filePath.
Is there any way to solve it? please.

**Comment by magnusja** [comment] 2017-06-06 08:12
Hey there,

nope unfortunately not. Because libaums cannot be integrated into the Android/Linux file handling :(

**Comment by fly7632785** [comment] 2017-06-13 03:20
Hey Magnusja
@magnusja 
May I ask you some questions?
There is no Api in android official developer web to operate the file system directly,isn't it?
Thanks to your open framework , I can read files from file system.
But I wanna know is there any other framework or official Api I didn't discover can operate files via filePath? 
After I checked the official Api , I figure it out that it transfers via bulkTransfer like socket, not via file system like your framework. right?
Why doesn't the official Api support it?

**Comment by magnusja** [comment] 2017-06-13 08:24
Hey there,

no there is no official Android API for accessing USB drives, but some devices mount USB drives and you can access them via the standard Java File API.
There is no API which exposes a file path, which is known to the rest of the OS, besides if the device mounts the drive on Linux kernel level.
The Android USB Host API offers very low level functionality in regards to USB (bulk transfer, ...). libaums implements several protocol layers to be able to expose a file system like API.

**Comment by fly7632785** [comment] 2017-06-13 08:27
@magnusja   
yes, what a great framework!
Thank you

**Comment by fly7632785** [comment] 2017-06-22 06:09
Hi,magnusja @magnusja 
You are one of great developers I know, I want to learn some from you. 
Maybe I ask you a few questions about usb equipment?
My Requirement:
I got a usb equipment(https://gyazo.com/d5c5288d0535ae83e9fb2cdb80adc55d), and I need read its files and upload files by android phone connecting to the usb equipment
But it can't  getPartitions, it's empty.
The usb equipment is Fat32.
As I know, the equipment maybe based on a linux system. So can I operate its file via Java File API? (besePath '/sys/bus/usb/devices/')
I know very little about linux usb equipment
hope get your help
thank you

**Comment by magnusja** [comment] 2017-06-22 06:21
If you are able to get a `UsbMassStorageDevice` via `getMassStorageDevices`, then your equipment should be fine. I am not sure what exactly is shown in that picture, but it says USB OTG and that is exactly what you need.
Are you sure that it is FAT32? 
Are you suing Linux or Windows? Maybe you can show me some details of the drive you are using.

**Comment by fly7632785** [comment] 2017-06-22 06:42
@magnusja  
The customer tells it's FAT32, but partitions are empty, that's weird. 
The usb equipment is not like a Usb storage
It can take photo and save it, if it connects to phone, then read files and upload.
Is there any way to judge it is FAT32 or not ?

**Comment by magnusja** [comment] 2017-06-22 06:48
Do you have a link to the product?
Hard to tell, can you use it on your computer?

**Comment by fly7632785** [comment] 2017-06-22 07:01
Sorry, I don't know now
I was confirming to the customer
The customer shows me some screenshots of APP( USB Device Info) connected to the usb equipment
![bfdeeba0-1caf-43f1-8e67-413ff1894baf](https://user-images.githubusercontent.com/10276266/27420980-f2391da8-575a-11e7-80d2-c81e2ea7ff47.png)
 
![4cbf1256-69e5-4b49-8014-78bb1b9ecb30](https://user-images.githubusercontent.com/10276266/27420998-06b2c036-575b-11e7-857f-38022c803176.png)

![06fd502f-8653-48d1-a0ca-bc70654497eb](https://user-images.githubusercontent.com/10276266/27421030-1ae68916-575b-11e7-9754-f3f6d2228b94.png)
![0a7e7851-e144-4d97-bd74-8d420b14ec90](https://user-images.githubusercontent.com/10276266/27421037-2634481c-575b-11e7-909c-a834aa498802.png)
![939acce8-8e1e-4d58-ad9f-ee97c95298e7](https://user-images.githubusercontent.com/10276266/27421049-30d58c22-575b-11e7-8da7-0aa1c64b4a19.png)

what can they tell us?
It can read the device info
Thank you for your patience again

**Comment by magnusja** [comment] 2017-06-22 07:09
Yeah, that only says it is a mass storage device. But it cannot say what kind of file system.
Best would be to have a website about the product to get more information.

**Comment by fly7632785** [comment] 2017-06-22 07:30
I will confirm it tomorrow 
If it's really not FAT32, how could I do?
0_0

**Comment by magnusja** [comment] 2017-06-22 07:42
Connect it to your computer and see what it says about the file system

**Comment by fly7632785** [comment] 2017-06-23 07:00
hi, Magnusja.
Sorry for bothering you, too
I have a question.
When I use a Usb storage, it works good. We can get device info via android Api. But can't get devices via linux path "/sys/bus/usb/devices"  (in APP USB Device info)
However, the customer's usb equipment can get device info via android Api and  linux path
![02cf7851-a4ba-4a9d-a8a9-4dfb10b359f5](https://user-images.githubusercontent.com/10276266/27469640-391fb966-5823-11e7-9ae9-30a38f87a979.png)
its device info in linux is like this:
![0036db19-f936-495f-9810-3b34b32ef79c](https://user-images.githubusercontent.com/10276266/27469669-582d2fc8-5823-11e7-9fb3-26fe13310994.png)

I want to know why?
Is the usb equipment a linux usb or something else? 
Why does it have 3 devices under the path of "/sys/bus/usb/devices/", but normal Usb storage has nothing?

**Comment by magnusja** [comment] 2017-06-23 07:12
A USB device can have multiple USB interfaces. Imagine a USB hub, it is a USB device itself but represents the devices you connect to it.

**Comment by fly7632785** [comment] 2017-06-23 08:17
yes, you are right 
So the usb equipment has a storage, too. Like a normal  Usb storage, we can access its fileSystem.
And its fileSystem type is FAT32, what can cause that it gets empty partition?

**Comment by magnusja** [comment] 2017-06-23 20:07
Usually, that is the case if the device is not formatted with an MBR and a file system supported by libaums.

So make 100% sure that this is the case. How do you know it is FAT32?

**Comment by fly7632785** [comment] 2017-06-25 03:35
Yes, it is FAT32. When I put it on the computer, it shows.
![mmexport1498361447721](https://user-images.githubusercontent.com/10276266/27513472-de1a9716-5999-11e7-919a-33035ee151ee.png)
![mmexport1498361469638](https://user-images.githubusercontent.com/10276266/27513473-e21120d8-5999-11e7-9acd-8e409f0b9b18.png)
Sorry, I just don't know how to do.

**Comment by magnusja** [comment] 2017-06-27 04:54
Can you maybe create an image for me and send it to me via email?
´dd if=/dev/YOURDRIVE of=usb.img bs=10m count=1´
Run the following command to get the path to your drive on a mac:
´diskutil list´

**Comment by fly7632785** [comment] 2017-06-28 06:40
what you mean is to connect Usb equipment to computer, and execute 'diskutil list'?  
As to 'dd if=...', I don't know what my drive is.
Should I execute 'dd if=....', too?
Sorry, and I don't know your email.

By the way, the Usb equipment can be read by the APP(https://play.google.com/store/apps/details?id=com.homeysoft.nexususb.importer&hl=ja)
The App is very great, I don't think I can implement the same app like that.So I can just count on your help.
Thank you

**Comment by fly7632785** [comment] 2017-06-28 06:58
The command result:
bin-no-MBP:temp bingao$ dd if=/Volumes/NO\ NAME/ of=usb.img bs=10 count=1
1+0 records in
1+0 records out
10 bytes transferred in 0.000082 secs (121927 bytes/sec)

B00???bin-no-MBP:temp bingao$ diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *251.0 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:          Apple_CoreStorage Macintosh HD            250.1 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3

/dev/disk1 (internal, virtual):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                  Apple_HFS Macintosh HD           +249.8 GB   disk1
                                 Logical Volume on disk0s2
                                 8ABB2546-043F-4E17-A20A-8EECAB36BE00
                                 Unlocked Encrypted

/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                            NO NAME                *7.9 GB     disk2

**Comment by fly7632785** [comment] 2017-06-28 07:00
The NO NAME is the USB equipment. 
Is there any valuable information?

**Comment by fly7632785** [comment] 2017-06-28 10:10
Hi, magnusja
There's a more info about the USB equipment.
It has a micro SD card  in it. Data is saved in it.
Is this reason that we can't read from it?

**Comment by fly7632785** [comment] 2017-06-28 10:20
Because I don't have your e-mail. Here is the usb.img file(http://jafir-my-love.oss-cn-shanghai.aliyuncs.com/usb.img)

**Comment by magnusja** [comment] 2017-06-28 14:40
Yes, I think SD card readers do not work at the moment for some reason. Maybe I find some time in the next couple of days to do some tests.

**Comment by fly7632785** [comment] 2017-06-29 01:34
OK, thank you!
You mean it originally supports it?
Is there anything I can do for you?

**Comment by fly7632785** [comment] 2017-06-29 04:14
http://jafir-my-love.oss-cn-shanghai.aliyuncs.com/log.txt
this is a log
It doesn't seem it has any abnormal log

**Comment by fly7632785** [comment] 2017-06-29 07:34
And  I  get some information.
![6c4e8926-619a-4698-a32c-9446d97cfa37](https://user-images.githubusercontent.com/10276266/27676395-5166f3ba-5ce0-11e7-8218-bf1247857959.png)
the partitionType is always 0  four times 
so 'result.partitions.add(entry) ' didn't execute.

**Comment by fly7632785** [comment] 2017-06-29 09:53
More information is that the USB equipment may doesn't have a MBR support 
![11f9040e-2b14-441d-aece-d2b1c1a32537 1](https://user-images.githubusercontent.com/10276266/27682070-d323719a-5cf3-11e7-99af-f16616cc009a.png)

**Closed** 2017-07-03 17:00 UTC

**Comment by honeyvinay95** [comment] 2020-02-20 11:25
I have made an application using "libaums" to get files from external device but  could not able to get the Path.

package com.example.usbread;

import androidx.appcompat.app.ActionBar;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;

import android.app.PendingIntent;
import android.content.BroadcastReceiver;
import android.content.ComponentName;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.ServiceConnection;
import android.hardware.usb.UsbDevice;
import android.hardware.usb.UsbManager;
import android.os.Bundle;
import android.os.IBinder;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.Button;
import android.widget.ListView;
import android.widget.Spinner;
import android.widget.Toast;

import com.github.mjdev.libaums.UsbMassStorageDevice;
import com.github.mjdev.libaums.fs.FileSystem;
import com.github.mjdev.libaums.fs.UsbFile;
import com.github.mjdev.libaums.server.http.UsbFileHttpServerService;
import com.koushikdutta.async.future.Cancellable;

import java.io.IOException;

public class MainActivity extends AppCompatActivity implements AdapterView.OnItemClickListener {
    private static final String ACTION_USB_PERMISSION = "com.example.usbread.USB_PERMISSION";
    private static final String TAG = "MemoryListing";
    private int currentDevice = -1;
    private FileSystem currentFs;
    private UsbFileHttpServerService serverService;
    UsbMassStorageDevice[] massStorageDevices;
    UsbFileListAdapter adapter;
    Spinner spinner;
    ListView list;
    Button button;

    private final BroadcastReceiver usbReceiver = new BroadcastReceiver() {      //Broadcast receiver is an Android component which allows you to send or receive Android system or application events

        @Override
        public void onReceive(Context context, Intent intent) {
    String action = intent.getAction();
			if (ACTION_USB_PERMISSION.equals(action)) {

        UsbDevice device = (UsbDevice) intent.getParcelableExtra(UsbManager.EXTRA_DEVICE);
        if (intent.getBooleanExtra(UsbManager.EXTRA_PERMISSION_GRANTED, false)) {

            if (device != null) {
                setupDevice();
            }
        }

    } else if (UsbManager.ACTION_USB_DEVICE_ATTACHED.equals(action)) {
        UsbDevice device = (UsbDevice) intent.getParcelableExtra(UsbManager.EXTRA_DEVICE);

        Log.d(TAG, "USB device attached");

        // determine if connected device is a mass storage devuce
        if (device != null) {
            discoverDevice();
        }
    } else if (UsbManager.ACTION_USB_DEVICE_DETACHED.equals(action)) {
        UsbDevice device = (UsbDevice) intent.getParcelableExtra(UsbManager.EXTRA_DEVICE);

                Log.d(TAG, "USB device detached");

        // determine if connected device is a mass storage devuce
        if (device != null) {
            if (MainActivity.this.currentDevice != -1) {
                MainActivity.this.massStorageDevices[currentDevice].close();
                ShowPopup();
            }

            // check if there are other devices or set action bar title
            // to no device if not
            discoverDevice();
        }
    }

}
	};

private void ShowPopup() {


        final AlertDialog.Builder builder = new AlertDialog.Builder(this);
        builder.setCancelable(false);
        builder.setTitle("Warning !");
        builder.setMessage("Your Usb is Detached !Click on confirm to try again ");

        builder.setPositiveButton("Confirm", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                new Cancellable() {
                    @Override
                    public boolean isDone() {
                        return false;
                    }

                    @Override
                    public boolean isCancelled() {
                        return false;
                    }

                    @Override
                    public boolean cancel() {
                        return false;
                    }
                };
            }
        });
        /*    builder.setNegativeButton("Cancel", new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int which) {
                    dialog.dismiss();
                }
            });*/
        builder.show();
    }


    ServiceConnection serviceConnection = new ServiceConnection() {
        @Override
        public void onServiceConnected(ComponentName name, IBinder service) {
            Log.d(TAG, "on service connected " + name);
            UsbFileHttpServerService.ServiceBinder binder = (UsbFileHttpServerService.ServiceBinder) service;
            serverService = binder.getService();
        }

        @Override
        public void onServiceDisconnected(ComponentName name) {
            Log.d(TAG, "on service disconnected " + name);
            serverService = null;
        }
    };




    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        spinner=findViewById(R.id.spinner);
        button=findViewById(R.id.button);
        list=findViewById(R.id.list);
        list.setOnItemClickListener(this);

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                setupDevice();
            }
        });
        registerForContextMenu(list);



        IntentFilter filter = new IntentFilter(ACTION_USB_PERMISSION);
        filter.addAction(UsbManager.ACTION_USB_DEVICE_ATTACHED);
        filter.addAction(UsbManager.ACTION_USB_DEVICE_DETACHED);
        registerReceiver(usbReceiver, filter);

        discoverDevice();

    }
  /*  @Override
    protected void onStart() {
        super.onStart();

        startService(serviceIntent);
        bindService(serviceIntent, serviceConnection, Context.BIND_AUTO_CREATE);
    }

    @Override
    protected void onStop() {
        super.onStop();

        unbindService(serviceConnection);
    }*/

    private void selectDevice(int position) {
        currentDevice = position;
        setupDevice();
    }


    private void discoverDevice() {
        UsbManager usbManager = (UsbManager) getSystemService(Context.USB_SERVICE);
        massStorageDevices = UsbMassStorageDevice.getMassStorageDevices(this);

        SpinnerAdapter aa=new SpinnerAdapter(this, android.R.layout.simple_spinner_item,massStorageDevices);
        //memoryListingBinding.spinner.setAdapter(new SpinnerAdapter(this,android.R.layout.simple_spinner_item, massStorageDevices));

        /*  Array aa=new Array[]();*/
        aa.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spinner.setAdapter(aa);
        /*  Log.d(TAG, "memory"+massStorageDevices);*/

        if (massStorageDevices.length == 0) {

            Log.w(TAG, "no device found!");
            androidx.appcompat.app.ActionBar actionBar = getSupportActionBar();
            actionBar.setTitle("No device");
            list.setAdapter(null);



            return;
        }else {
            massStorageDevices[0].getUsbDevice();


        }



     //   memoryListview.setItemChecked(0, true);
        currentDevice = 0;

        UsbDevice usbDevice = massStorageDevices[0].getUsbDevice();

        //String s=usbDevice.getDeviceName();
      //  Toast.makeText(context, "list: "+s, Toast.LENGTH_SHORT).show();

        // UsbDevice usbDevice = (UsbDevice) getIntent().getParcelableExtra(UsbManager.EXTRA_DEVICE);

        if (usbDevice != null && usbManager.hasPermission(usbDevice)) {
            Log.d(TAG, "received usb device via intent");
            // requesting permission is not needed in this case
            setupDevice();
        } else {
            // first request permission from user to communicate with the
            // underlying
            // UsbDevice
            PendingIntent permissionIntent = PendingIntent.getBroadcast(this, 0, new Intent(
                    ACTION_USB_PERMISSION), 0);
            usbManager.requestPermission(massStorageDevices[currentDevice].getUsbDevice(), permissionIntent);
        }


    }

    private void setupDevice() {
        try {
            massStorageDevices[currentDevice].init();

            // we always use the first partition of the device
            currentFs = massStorageDevices[currentDevice].getPartitions().get(0).getFileSystem();
            Log.d(TAG, "Capacity: " + currentFs.getCapacity());
            Log.d(TAG, "Occupied Space: " + currentFs.getOccupiedSpace());
            Log.d(TAG, "Free Space: " + currentFs.getFreeSpace());
            Log.d(TAG, "Chunk size: " + currentFs.getChunkSize());
            UsbFile root = currentFs.getRootDirectory();

            Toast.makeText(this,currentFs.toString(),Toast.LENGTH_LONG).show();
            Log.d("testing",root.toString());

            ActionBar actionBar = getSupportActionBar();
            actionBar.setTitle(currentFs.getVolumeLabel());

            list.setAdapter(adapter = new UsbFileListAdapter(this, root));
        } catch (IOException e) {
            Log.e(TAG, "error setting up device", e);
        }

    }

    @Override
    public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {
        setupDevice();
    }
}


![Screenshot_2020-02-20-13-37-04](https://user-images.githubusercontent.com/29648246/74929516-afd69e80-5401-11ea-8905-20cdb219c141.png)

**Comment by magnusja** [comment] 2020-02-20 13:22
See `UsbFile.getAbsolutePath()`

**Comment by honeyvinay95** [comment] 2020-02-21 09:35
@magnusja  I have searched getAbsolutePath in UsbFile interface but you did not define any this method in your interface 
![2020-02-21](https://user-images.githubusercontent.com/29648246/75022146-91cd7480-54bb-11ea-8d16-5607e23d590c.png)

**Comment by magnusja** [comment] 2020-02-21 10:11
You are using a pretty old version.
https://github.com/magnusja/libaums/blob/develop/libaums/src/main/java/com/github/mjdev/libaums/fs/UsbFile.kt#L63

**Comment by honeyvinay95** [comment] 2020-02-21 15:12
Hi @magnusja I have searched everywhere how to get the Path of an External Device could not find any solution :(  The issue is when I connect USB to android device I got a list of files which is inside my USB stick and want to show the Path of an Each file which is inside my USB stick like this storage/USB A/filename but I could not able to get the path I hope you will resolve my problem my last hope is you......

**Comment by magnusja** [comment] 2020-02-21 15:57
Not sure what you need. You get the absolute path and then you can prepend the USB devices name or waht not if you want and show that to make it clear it is on a USB device.

**Comment by honeyvinay95** [comment] 2020-02-22 09:55
> You are using a pretty old version.
> https://github.com/magnusja/libaums/blob/develop/libaums/src/main/java/com/github/mjdev/libaums/fs/UsbFile.kt#L63

![2020-02-22](https://user-images.githubusercontent.com/29648246/75090250-e8ec4b80-5586-11ea-9646-972bdb386e7d.png)

I'm using Java i dont have any idea of Kotlin

**Comment by honeyvinay95** [comment] 2020-02-22 10:57
> Not sure what you need. You get the absolute path and then you can prepend the USB devices name or waht not if you want and show that to make it clear it is on a USB device.

I want to get absolute path of an External Device or USB, When I connect the USB to android Device it will show me the Path like the below image:
![Zip_ES_File_Explorer (1)](https://user-images.githubusercontent.com/29648246/75091000-afb7d980-558e-11ea-96c0-bc68ac516b75.jpeg)


![123](https://user-images.githubusercontent.com/29648246/75091148-2e614680-5590-11ea-99d7-94206a4888c1.png)

**Comment by honeyvinay95** [comment] 2020-02-24 08:12
@magnusja 


![2020-02-22](https://user-images.githubusercontent.com/29648246/75133607-76ec4180-5701-11ea-9dd1-75de44311b63.png)

**Comment by magnusja** [comment] 2020-02-24 10:01
If this is only for displaying purposes I would go with the solution I posted earlier. 

There is no Android accessible path when your are using libaums. It is just technically not feasible.

**Comment by honeyvinay95** [comment] 2020-02-24 10:27
@magnusja By mistake I wrote the wrong  sentence pardon my English but I need to get External Storage Path. In my code I have tried so many ways to get the External Storage Path getAbsolutePath(),  getRootDirectory() and Environment.getExternalStorageDirectory() but could not able to get the External Storage Path

**Comment by magnusja** [comment] 2020-02-24 11:15
No you are not.

You can get the absolute path within a USB directory described in #38.

The general Android USB path is out of scope for this library. There are devices which support that and some other do not. The question is why would you need the path? If you only want to display it, why does it need to be the Android USB path, why not something else where the user gets the idea that the file is in some folder on the USB drive.

**Comment by honeyvinay95** [comment] 2020-02-27 05:18
Thank you @magnusja  finally got the path :)

**Comment by Shantanu-tec** [comment] 2022-08-06 09:25
Hi,
I am using this library to get the contents stored in the USB. It is working fine.
But when i need to decrypt the content or play the content. I need an absolute path of the USB in android file system.

Can you guys please help me.

**Comment by surjansinghdonkeli** [comment] 2023-03-18 08:01
![WhatsApp Image 2023-03-18 at 1 27 11 PM](https://user-images.githubusercontent.com/30921018/226093335-dab4fa1d-d33f-43d9-81d8-04d5e1367729.jpeg)

Sir I have found pendrive path but folder is not able to be found please help me thanks sir

**Comment by surjansinghdonkeli** [comment] 2023-03-18 08:01
using this code


 public void listDirectory(String dirPath, int level) {
        File dir = new File(dirPath);
        

        Toast.makeText(getApplicationContext(),  String.valueOf(dir), Toast.LENGTH_SHORT).show();
        
        File[] firstLevelFiles = dir.listFiles();
        if (firstLevelFiles != null && firstLevelFiles.length > 0) {
            for (File aFile : firstLevelFiles) {
                for (int i = 0; i < level; i++) {
                    System.out.print("\t");
                }
                if (aFile.isDirectory()) {
                    System.out.println("[" + aFile.getName() + "]");
                    
                    
                    listDirectory(aFile.getAbsolutePath(), level + 1);
                } else {
                    System.out.println(aFile.getName());
                    
                    
                    
                    
                }
            }
        }
}

**Comment by magnusja** [comment] 2023-03-20 14:52
You are not even using this library?! Why would you ask that here. Please ask that on stackoverflow or sth ...

**Comment by surjansinghdonkeli** [comment] 2023-03-24 07:24
Sir Your Library Display This

![page](https://user-images.githubusercontent.com/30921018/227452782-fface503-d310-47d9-8e4d-38def3bdb70b.png)

**Comment by surjansinghdonkeli** [comment] 2023-03-24 07:27
Dear Sir,
             My requirement Data Copy Pen drive to Mobile Device. How Can Possible. Please Suggest Me as Soon as Possible.

Thanks & Regards,
Surjan Singh
9958715332

**Comment by magnusja** [comment] 2023-03-24 10:03
That is an old link https://github.com/magnusja/libaums/blob/develop/libaums/src/main/java/me/jahnen/libaums/core/fs/UsbFile.kt

Please consult the documentation it is all explained there. In addition, try the example application from this repository.
